# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy', '0002_auto_20180323_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='travelbuddy.User'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(related_name='trips', to='travelbuddy.User'),
        ),
    ]
